apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  replicas: 10
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - image: nginx
          name: nginx
          resources:
            requests:
              cpu: "1m"  # Request 50 millicores of CPU
              memory: "1Mi"  # Request 50 MiB of memory
            limits:
              cpu: "1m"  # Limit to 100 millicores of CPU
              memory: "1Mi"  # Limit to 100 MiB of memory
